import Head from 'next/head'
import { Inter } from 'next/font/google'
import "@narmi/design_system/dist/style.css";

import { ContentCard, SeparatorList } from "@narmi/design_system";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NDS Consumer: Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="padding--all--xl nds-typography bgColor--blueGrey" style={{ minHeight: "100vh" }}>
        <h1 className="margin--bottom fontSize--heading0">Narmi Design System + Next.js v14</h1>
        <ContentCard kind="elevated">
          <SeparatorList items={4} />
        </ContentCard>
      </main>
    </>
  )
}
